// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy9O4CSJMFmViYTx8DXeS9afmHpe3cLoY',
    appId: '1:909773411302:web:e0316d9528f20b03bdfc27',
    messagingSenderId: '909773411302',
    projectId: 'msg-prep',
    authDomain: 'msg-prep.firebaseapp.com',
    databaseURL: 'https://msg-prep-default-rtdb.firebaseio.com',
    storageBucket: 'msg-prep.appspot.com',
    measurementId: 'G-N5TE742PNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTG3IjZtfLafAZoL2ZrRTdPRPYXNMOWXY',
    appId: '1:909773411302:android:9d7faf1040cd28c5bdfc27',
    messagingSenderId: '909773411302',
    projectId: 'msg-prep',
    databaseURL: 'https://msg-prep-default-rtdb.firebaseio.com',
    storageBucket: 'msg-prep.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQrthgOoLffUNTgXc1-3r9seiU0LsXFMc',
    appId: '1:909773411302:ios:b770d72ee29a9fe5bdfc27',
    messagingSenderId: '909773411302',
    projectId: 'msg-prep',
    databaseURL: 'https://msg-prep-default-rtdb.firebaseio.com',
    storageBucket: 'msg-prep.appspot.com',
    iosBundleId: 'com.example.chatappfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQrthgOoLffUNTgXc1-3r9seiU0LsXFMc',
    appId: '1:909773411302:ios:b770d72ee29a9fe5bdfc27',
    messagingSenderId: '909773411302',
    projectId: 'msg-prep',
    databaseURL: 'https://msg-prep-default-rtdb.firebaseio.com',
    storageBucket: 'msg-prep.appspot.com',
    iosBundleId: 'com.example.chatappfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy9O4CSJMFmViYTx8DXeS9afmHpe3cLoY',
    appId: '1:909773411302:web:db0af4e722ddec30bdfc27',
    messagingSenderId: '909773411302',
    projectId: 'msg-prep',
    authDomain: 'msg-prep.firebaseapp.com',
    databaseURL: 'https://msg-prep-default-rtdb.firebaseio.com',
    storageBucket: 'msg-prep.appspot.com',
    measurementId: 'G-941ME8FTPW',
  );

}